DemoApp.WebUI/Models/ErrorViewModel.cs
namespace DemoApp.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoApp.WebUI/Models/ExamModel.cs
using DemoApp.Business.DataTransferObjects;

namespace DemoApp.WebUI.Models;

public class ExamModel : ModelBase<ExamDto>
{
	public ICollection<LessonDto> Lessons { get; set; }

	public ICollection<StudentDto> Students { get; set; }
}

DemoApp.WebUI/Models/ModelBase.cs
namespace DemoApp.WebUI.Models;

public class ModelBase<T>
{
	public T Data { get; set; }

	public ICollection<string> ErrorMessages { get; set; } = new List<string>();

	public bool IsEdit { get; set; }
}

DemoApp.WebUI/Controllers/ExamsController.cs
using DemoApp.Business;
using DemoApp.Business.DataTransferObjects;
using DemoApp.Business.Services;
using DemoApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoApp.WebUI.Controllers;

public class ExamsController : Controller
{
	private readonly IExamService _examService;
	private readonly ILessonService _lessonService;
	private readonly IStudentService _studentService;

	public ExamsController(
		IExamService examService,
		ILessonService lessonService,
		IStudentService studentService)
	{
		_examService = examService;
		_lessonService = lessonService;
		_studentService = studentService;
	}

	public async Task<IActionResult> Index()
	{
		var data = (await _examService.GetAllAsync()).Data;

		return View(new ModelBase<ICollection<ExamDto>>
		{
			Data = data
		});
	}

	public async Task<IActionResult> Add()
	{
		var model = await CreateModelAsync();
		model.Data = new ExamDto
		{
			ExamDate = DateTime.Now
		};

		return View("Exam", model);
	}

	public async Task<IActionResult> Edit(int id)
	{
		var result  = await _examService.GetByIdAsync(id);

		if (result.ResultState != ResultState.Success)
		{
			return RedirectToAction("Index");
		}

		var model = await CreateModelAsync();
		model.Data = result.Data!;
		model.IsEdit = true;

		return View("Exam", model);
	}

	public async Task<IActionResult> Delete(int id)
	{
		var result = await _examService.DeleteAsync(id);
		var data = (await _examService.GetAllAsync()).Data;


		if (result.ResultState == ResultState.Success)
		{
			return RedirectToAction("Index");
		}

		return View("Index", new ModelBase<ICollection<ExamDto>>
		{
			Data = data,
			ErrorMessages = result.Messages
		});
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Add(ExamModel model)
	{
		var result = await _examService.AddAsync(model.Data);

		if (result.ResultState != ResultState.Success)
		{
			var data = model.Data;
			model = await CreateModelAsync();
			model.Data = data;
			model.ErrorMessages = result.Messages;

			return View("Exam", model);
		}

		return RedirectToAction("Index");
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Edit(ExamModel model)
	{
		var result = await _examService.UpdateAsync(model.Data);

		if (result.ResultState != ResultState.Success)
		{
			var data = model.Data;
			model = await CreateModelAsync();
			model.Data = data;
			model.ErrorMessages = result.Messages;
			model.IsEdit = true;

			return View("Exam", model);
		}

		return RedirectToAction("Index");
	}

	private async Task<ExamModel> CreateModelAsync()
	{
		var students = await _studentService.GetAllAsync();
		var lessons = await _lessonService.GetAllAsync();

		return new ExamModel
		{
			Students = students.Data,
			Lessons = lessons.Data
		};
	}
}

DemoApp.WebUI/Controllers/HomeController.cs
using DemoApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoApp.WebUI/Controllers/LessonsController.cs
using DemoApp.Business;
using DemoApp.Business.DataTransferObjects;
using DemoApp.Business.Services;
using DemoApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoApp.WebUI.Controllers;

public class LessonsController : Controller
{
	private readonly ILessonService _lessonService;

	public LessonsController(
		ILessonService lessonService)
	{
		_lessonService = lessonService;
	}

	public async Task<IActionResult> Index()
	{
		var data = (await _lessonService.GetAllAsync()).Data;

		return View(new ModelBase<ICollection<LessonDto>>
		{
			Data = data
		});
	}

	public IActionResult Add()
	{
		return View("Lesson", new ModelBase<LessonDto>
		{
			Data = new LessonDto()
		});
	}

	public async Task<IActionResult> Edit(string code)
	{
		var result = await _lessonService.GetByCodeAsync(code);

		if (result.ResultState != ResultState.Success)
		{
			return RedirectToAction("Index");
		}

		var studentModel = new ModelBase<LessonDto>
		{
			Data = result.Data!,
			ErrorMessages = result.Messages,
			IsEdit = true
		};

		return View("Lesson", studentModel);
	}

	public async Task<IActionResult> Delete(string code)
	{
		var result = await _lessonService.DeleteAsync(code);
		var data = (await _lessonService.GetAllAsync()).Data;

		if (result.ResultState == ResultState.Success)
		{
			return RedirectToAction("Index");
		}

		return View("Index", new ModelBase<ICollection<LessonDto>>
		{
			Data = data,
			ErrorMessages = result.Messages
		});
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Add(ModelBase<LessonDto> lessonModel)
	{
		var result = await _lessonService.AddAsync(lessonModel.Data);

		if (result.ResultState != ResultState.Success)
		{
			lessonModel.ErrorMessages = result.Messages;

			return View("Lesson", lessonModel);
		}

		return RedirectToAction("Index");
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Edit(ModelBase<LessonDto> lessonModel)
	{
		var result = await _lessonService.UpdateAsync(lessonModel.Data);

		if (result.ResultState != ResultState.Success)
		{
			lessonModel.ErrorMessages = result.Messages;
			lessonModel.IsEdit = true;

			return View("Lesson", lessonModel);
		}

		return RedirectToAction("Index");
	}
}

DemoApp.WebUI/Controllers/StudentsController.cs
using DemoApp.Business;
using DemoApp.Business.DataTransferObjects;
using DemoApp.Business.Services;
using DemoApp.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace DemoApp.WebUI.Controllers;

public class StudentsController : Controller
{
    private readonly IStudentService _studentService;

    public StudentsController(
        IStudentService studentService)
    {
        _studentService = studentService;
    }

	public async Task<IActionResult> Index()
	{
		var data = (await _studentService.GetAllAsync()).Data;

		return View(new ModelBase<ICollection<StudentDto>>
		{ 
			Data = data
		});
	}

	public IActionResult Add()
	{
		return View("Student", new ModelBase<StudentDto>
		{
			Data = new StudentDto()
		});
	}

	public async Task<IActionResult> Edit(int number)
	{
		var result = await _studentService.GetByNumberAsync(number);

		if (result.ResultState != ResultState.Success)
		{
			return RedirectToAction("Index");
		}

		var studentModel = new ModelBase<StudentDto>
		{
			Data = result.Data!,
			ErrorMessages = result.Messages,
			IsEdit = true
		};

		return View("Student", studentModel);
	}

	public async Task<IActionResult> Delete(int number)
	{
		var result = await _studentService.DeleteAsync(number);
		var data = (await _studentService.GetAllAsync()).Data;

		if (result.ResultState == ResultState.Success)
		{
			return RedirectToAction("Index");
		}


		return View("Index", new ModelBase<ICollection<StudentDto>>
		{
			Data = data,
			ErrorMessages = result.Messages
		});
	}

	[HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Add(ModelBase<StudentDto> studentModel)
    {
        var result = await _studentService.AddAsync(studentModel.Data);

        if (result.ResultState != ResultState.Success)
        {
	        studentModel.ErrorMessages = result.Messages;

	        return View("Student", studentModel);
		}

        return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(ModelBase<StudentDto> studentModel)
    {
	    var result = await _studentService.UpdateAsync(studentModel.Data);

	    if (result.ResultState != ResultState.Success)
	    {
		    studentModel.ErrorMessages = result.Messages;
		    studentModel.IsEdit = true;

		    return View("Student", studentModel);
	    }

	    return RedirectToAction("Index");
    }
}

DemoApp.WebUI/Views/Exams/Exam.cshtml
@model DemoApp.WebUI.Models.ExamModel
@{
}

@if (Model.ErrorMessages.Any())
{
	<div class="m-2">
		@foreach (var message in Model.ErrorMessages)
		{
			<p class="text-danger mb-0">* @message</p>
		}
	</div>
}

@using (Html.BeginForm(Model.IsEdit ? "Edit" : "Add", "Exams", null, FormMethod.Post, true, null))
{
	<input type="hidden" asp-for="Data.Id" value="@Model.Data.Id"/>
	<div class="row">
		<div class="col-sm-3">
			<label>Dərsin adı:</label>
			<select class="form-select" required="true" asp-for="Data.LessonCode">
				@foreach (var lesson in Model.Lessons)
				{
					<option value="@lesson.Code">@lesson.Name</option>
				}
			</select>
		</div>
		<div class="col-sm-3">
			<label>Şagirdin adı:</label>
			<select class="form-select" required="true" asp-for="Data.StudentNumber">
				@foreach (var student in Model.Students)
				{
					<option value="@student.Number">@($"{student.Name} {student.Surname}")</option>
				}
			</select>
		</div>
		<div class="col-sm-3">
			<label>İmtahan tarixi:</label>
			<input type="date" class="form-control" asp-for="Data.ExamDate" required="true" value="@Model.Data.ExamDate.ToString("yyyy-MM-dd")" />
		</div>
		<div class="col-sm-3">
			<label>Qiyməti:</label>
			@Html.TextBoxFor(x => x.Data.Score, new
			{
				@class = "form-control",
				@type = "number",
				@required = true
			})
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12 text-end mt-3">
			<button class="btn btn-primary" type="submit">Yadda Saxla</button>
		</div>
	</div>
}

DemoApp.WebUI/Views/Exams/Index.cshtml
@model ModelBase<ICollection<DemoApp.Business.DataTransferObjects.ExamDto>>
@{
	ViewData["Title"] = "İmtahanlar";
}

<h2 class="mb-5">@ViewData["Title"]</h2>

@if (Model.ErrorMessages.Any())
{
	<div class="m-2">
		@foreach (var message in Model.ErrorMessages)
		{
			<p class="text-danger mb-0">* @message</p>
		}
	</div>
}

<div class="row">
	<div class="col-sm-12 text-end">
		<a class="btn btn-primary" asp-action="Add">Əlavə et</a>
	</div>
</div>

<table class="table table-bordered table-striped mt-3" style="width: 100%">
	<thead>
	<tr>
		<th class="text-center">Dərsin adı</th>
		<th class="text-center">Şagirdin adı</th>
		<th class="text-center">İmtahan tarixi</th>
		<th class="text-center">Qiyməti</th>
		<th style="width: 10%"></th>
	</tr>
	</thead>
	<tbody>
	@foreach (var dto in Model.Data)
	{
		<tr>
			<td class="p-1">@dto.LessonFullName</td>
			<td class="p-1">@dto.StudentFullName</td>
			<td class="p-1">@dto.ExamDate.ToString("yyyy-MM-dd")</td>
			<td class="p-1">@dto.Score</td>
			<td>
				<a class="btn btn-warning" asp-action="Edit" asp-route-id="@dto.Id">Dəyiş</a>
				<a class="btn btn-danger" asp-action="Delete" asp-route-id="@dto.Id">Sil</a>
			</td>
		</tr>
	}
	</tbody>
</table>

DemoApp.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Səhifə";
}

<div class="d-flex justify-content-center">
	<div class="card mx-3 shadow" style="width: 18rem;">
		<div class="card-body">
			<h4 class="card-title text-center">
				<a class="link" asp-controller="Lessons" asp-action="Index">Dərslər</a>
			</h4>
		</div>
	</div>
	<div class="card mx-3 shadow" style="width: 18rem;">
		<div class="card-body">
			<h4 class="card-title text-center">
				<a asp-controller="Students" asp-action="Index">Şagirdlər</a>
			</h4>
		</div>
	</div>
	<div class="card mx-3 shadow" style="width: 18rem;">
		<div class="card-body">
			<h4 class="card-title text-center">
				<a asp-controller="Exams" asp-action="Index">İmtahanlar</a>
			</h4>
		</div>
	</div>
</div>

DemoApp.WebUI/Views/Lessons/Index.cshtml
@model ModelBase<ICollection<DemoApp.Business.DataTransferObjects.LessonDto>>
@{

	ViewData["Title"] = "Dərslər";
}

<h2 class="mb-5">@ViewData["Title"]</h2>

@if (Model.ErrorMessages.Any())
{
	<div class="m-2">
		@foreach (var message in Model.ErrorMessages)
		{
			<p class="text-danger mb-0">* @message</p>
		}
	</div>
}

<div class="row">
	<div class="col-sm-12 text-end">
		<a class="btn btn-primary" asp-action="Add">Əlavə et</a>
	</div>
</div>

<table class="table table-bordered table-striped mt-3" style="width: 100%">
	<thead>
		<tr>
			<th class="text-center">Kodu</th>
			<th class="text-center">Adı</th>
			<th class="text-center">Sinfi</th>
			<th class="text-center">Müəllimin adı</th>
			<th class="text-center">Müəllimin soyadı</th>
			<th style="width: 10%"></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var dto in Model.Data)
		{
			<tr>
				<td class="p-1">@dto.Code</td>
				<td class="p-1">@dto.Name</td>
				<td class="p-1">@dto.Class</td>
				<td class="p-1">@dto.TeacherName</td>
				<td class="p-1">@dto.TeacherSurname</td>
				<td>
					<a class="btn btn-warning" asp-action="Edit" asp-route-code="@dto.Code">Dəyiş</a>
					<a class="btn btn-danger" asp-action="Delete" asp-route-code="@dto.Code">Sil</a>
				</td>
			</tr>
		}
	</tbody>
</table>

DemoApp.WebUI/Views/Lessons/Lesson.cshtml
@model DemoApp.WebUI.Models.ModelBase<DemoApp.Business.DataTransferObjects.LessonDto>
@{
}

@if (Model.ErrorMessages.Any())
{
	<div class="m-2">
		@foreach (var message in Model.ErrorMessages)
		{
			<p class="text-danger mb-0">* @message</p>
		}
	</div>
}

@using (Html.BeginForm(Model.IsEdit ? "Edit" : "Add", "Lessons", null, FormMethod.Post, true, null))
{
	<div class="row">
		<div class="col-sm-2">
			<label>Dərsin kodu:</label>
			@Html.TextBoxFor(x => x.Data.Code, Model.IsEdit ? new
			{
				@class = "form-control",
				@required = true,
				@readonly = true
			} : new
			{
				@class = "form-control",
				@required = true
			})
		</div>
		<div class="col-sm-3">
			<label>Dərsin adı:</label>
			@Html.TextBoxFor(x => x.Data.Name, new
			{
				@class = "form-control",
				@required = true
			})
		</div>
		<div class="col-sm-1">
			<label>Sinifi:</label>
			@Html.TextBoxFor(x => x.Data.Class, new
			{
				@class = "form-control",
				@type = "number",
				@required = true
			})
		</div>
		<div class="col-sm-3">
			<label>Dərsi verən müəllimin adı:</label>
			@Html.TextBoxFor(x => x.Data.TeacherName, new
			{
				@class = "form-control",
				@required = true
			})
		</div>
		<div class="col-sm-3">
			<label>Dərsi verən müəllimin soyadı:</label>
			@Html.TextBoxFor(x => x.Data.TeacherSurname, new
			{
				@class = "form-control",
				@required = true
			})
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12 text-end mt-3">
			<button class="btn btn-primary" type="submit">Yadda Saxla</button>
		</div>
	</div>
}

DemoApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - İmtahan proqramı</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoApp.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">İmtahan proqramı</a>
	            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
	                    aria-expanded="false" aria-label="Toggle navigation">
		            <span class="navbar-toggler-icon"></span>
	            </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
	                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lessons" asp-action="Index">Dərslər</a>
	                    </li>
	                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Şagirdlər</a>
	                    </li>
	                    <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exams" asp-action="Index">İmtahanlar</a>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DemoApp.WebUI/Views/Students/Index.cshtml
@model ModelBase<ICollection<DemoApp.Business.DataTransferObjects.StudentDto>>
@{
	
	ViewData["Title"] = "Şagirdlər";
}

<h2 class="mb-5">@ViewData["Title"]</h2>

@if (Model.ErrorMessages.Any())
{
	<div class="m-2">
		@foreach (var message in Model.ErrorMessages)
		{
			<p class="text-danger mb-0">* @message</p>
		}
	</div>
}

<div class="row">
	<div class="col-sm-12 text-end">
		<a class="btn btn-primary" asp-action="Add">Əlavə et</a>
	</div>
</div>

<table class="table table-bordered table-striped mt-3" style="width: 100%">
	<thead>
		<tr>
			<th class="text-center">Nömrəsi</th>
			<th class="text-center">Adı</th>
			<th class="text-center">Soyadı</th>
			<th class="text-center">Sinfi</th>
			<th style="width: 10%"></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var dto in Model.Data)
		{
			<tr>
				<td class="p-1">@dto.Number</td>
				<td class="p-1">@dto.Name</td>
				<td class="p-1">@dto.Surname</td>
				<td class="p-1">@dto.Class</td>
				<td>
					<a class="btn btn-warning" asp-action="Edit" asp-route-number="@dto.Number">Dəyiş</a>
					<a class="btn btn-danger" asp-action="Delete" asp-route-number="@dto.Number">Sil</a>
				</td>
			</tr>
		}
	</tbody>
</table>

DemoApp.WebUI/Views/Students/Student.cshtml
@model DemoApp.WebUI.Models.ModelBase<DemoApp.Business.DataTransferObjects.StudentDto>
@{
}

@if (Model.ErrorMessages.Any())
{
	<div class="m-2">
		@foreach (var message in Model.ErrorMessages)
		{
			<p class="text-danger mb-0">* @message</p>
		}
	</div>
}

@using (Html.BeginForm(Model.IsEdit ? "Edit" : "Add", "Students", null, FormMethod.Post, true, null))
{
	<div class="row">
		<div class="col-sm-3">
			<label>Şagirdin nömrəsi:</label>
			@Html.TextBoxFor(x => x.Data.Number, Model.IsEdit ? new
		{
		@class = "form-control",
		@type = "number",
		@required = true,
		@readonly = true
		} : new
		{
		@class = "form-control",
		@type = "number",
		@required = true
		})
		</div>
		<div class="col-sm-3">
			<label>Şagirdin adı:</label>
			@Html.TextBoxFor(x => x.Data.Name, new
		{
		@class = "form-control",
		@required = true
		})
		</div>
		<div class="col-sm-3">
			<label>Şagirdin soyadı:</label>
			@Html.TextBoxFor(x => x.Data.Surname, new
		{
		@class = "form-control",
		@required = true
		})
		</div>
		<div class="col-sm-3">
			<label>Sinifi:</label>
			@Html.TextBoxFor(x => x.Data.Class, new
		{
		@class = "form-control",
		@type = "number",
		@required = true
		})
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12 text-end mt-3">
			<button class="btn btn-primary" type="submit">Yadda Saxla</button>
		</div>
	</div>
}